trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: demo-agent
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          wget "https://sca-downloads.s3.amazonaws.com/cli/2.12.7/ScaResolver-linux64.tar.gz"
      displayName: 'Download sca-resolver'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          tar -xzvf "ScaResolver-linux64.tar.gz"
      displayName: 'unzip sca-resolver'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          rm -rf "ScaResolver-linux64.tar.gz"
      displayName: 'remove tar file'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          wget https://github.com/Checkmarx/ast-cli/releases/download/2.3.24/ast-cli_linux_x64.tar.gz
          # wget https://github.com/hitesh2310/ast-cli-linux-bin/archive/refs/tags/v1.0.tar.gz
      displayName: 'Download AST-CLI'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          tar -xzvf ast-cli_linux_x64.tar.gz
          # tar -xzvf v1.0.tar.gz
          # cp  ./ast-cli-linux-bin-1.0/cx .
      displayName: 'unzip AST-CLI'  
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          rm -rf "ast-cli_linux_x64.tar.gz"
          # rm -rf "v1.0.tar.gz"
      displayName: 'remove AST-CLI tar file'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          wget https://github.com/hitesh2310/ado-src/archive/refs/tags/v1.0.tar.gz
      displayName: 'Download repo'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          tar -xzvf "v1.0.tar.gz"
      displayName: 'unzip repo'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          rm -rf "v1.0.tar.gz"
      displayName: 'remove repo tar file'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # chmod +x ./cx
          echo $env:apiKey
          ./cx scan create  --apikey  eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlY2RkYmY4OS01MGNhLTQ2ZjMtYjIzMC02NjVlYWU5NWYzZTkifQ.eyJpYXQiOjE3NDg1MjU5NzQsImp0aSI6ImRiYTEwN2UzLTFiZjMtNGVmOC1iMjI3LWVkMWMyOTY4NGM0NCIsImlzcyI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvY3hfc2VnIiwiYXVkIjoiaHR0cHM6Ly9ldS5pYW0uY2hlY2ttYXJ4Lm5ldC9hdXRoL3JlYWxtcy9jeF9zZWciLCJzdWIiOiJjYmUzMDE2OS05YWM0LTRmNTMtYWQ5ZS0xNzk2ZWJiODgxNDkiLCJ0eXAiOiJPZmZsaW5lIiwiYXpwIjoiYXN0LWFwcCIsInNpZCI6IjRlMDgyYTM0LTU0ZmUtNDY1NC04MTNjLTgxOTk2Y2YyM2Y5YSIsInNjb3BlIjoicHJvZmlsZSBhc3QtYXBpIHJvbGVzIGdyb3VwcyBlbWFpbCBpYW0tYXBpIG9mZmxpbmVfYWNjZXNzIn0.O6zVcxg19AOGxDq_ePgY42KTOIEJ84B46nv-TwTowlkwd65sW83iWHpC0NcKe0SwJujy927FH-J-h6u-3OOEkA --project-name "headcount" --branch main --scan-types sca -s "./ado-src-1.0" --sca-resolver "./ScaResolver" --sca-resolver-params "--gradle-parameters='-Prepository.proxy.url=123 -Prepository.proxy.username=123 -Prepository.proxy.password=123' --log-level Debug"
      displayName: 'Execute SCA scan'
 